services:
    frontend:
        container_name: frontend
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/frontend/
            - /frontend/node_modules
        ports:
            - "3000:3000"
        networks:
            - rsaweb
        tty: true

networks:
    rsaweb:
        name: rsaweb
        external: true